package rocks.minestom.worldgen.verify;

import net.minestom.server.MinecraftServer;
import net.minestom.server.instance.block.Block;
import rocks.minestom.worldgen.WorldGenerators;

import java.nio.file.Path;
import java.util.TreeMap;

/** Prints a summary of blocks generated by our engine within a box, for diagnosing missing structure writes. */
public final class BlockBoxPeek {
    public static void main(String[] args) throws Exception {
        var datapackDir = Path.of(args[0]);
        var seed = Long.parseLong(args[1]);
        var minX = Integer.parseInt(args[2]);
        var minY = Integer.parseInt(args[3]);
        var minZ = Integer.parseInt(args[4]);
        var maxX = Integer.parseInt(args[5]);
        var maxY = Integer.parseInt(args[6]);
        var maxZ = Integer.parseInt(args[7]);

        var generators = new WorldGenerators(datapackDir, seed);
        MinecraftServer.init();
        var instance = MinecraftServer.getInstanceManager().createInstanceContainer();
        instance.setGenerator(generators.overworld());

        var minChunkX = minX >> 4;
        var maxChunkX = maxX >> 4;
        var minChunkZ = minZ >> 4;
        var maxChunkZ = maxZ >> 4;
        for (var chunkX = minChunkX - 1; chunkX <= maxChunkX + 1; chunkX++) {
            for (var chunkZ = minChunkZ - 1; chunkZ <= maxChunkZ + 1; chunkZ++) {
                instance.loadChunk(chunkX, chunkZ).join();
            }
        }

        var perPosition = Boolean.getBoolean("blockbox.perPosition");
        var counts = new TreeMap<String, Integer>();
        for (var x = minX; x <= maxX; x++) {
            for (var y = minY; y <= maxY; y++) {
                for (var z = minZ; z <= maxZ; z++) {
                    var block = instance.getBlock(x, y, z);
                    if (perPosition) {
                        System.out.println(x + "," + y + "," + z + " " + block);
                    }
                    counts.merge(block.key().asString(), 1, Integer::sum);
                }
            }
        }
        counts.forEach((key, count) -> System.out.printf("%8d  %s%n", count, key));
        System.exit(0);
    }
}
