name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Add execute permissions for gradlew
        run: chmod +x gradlew

      - name: Cache vanilla server
        uses: actions/cache@v4
        with:
          path: data/mc/26.2
          key: mc-26.2-v1

      - name: Build with Gradle
        run: ./gradlew build
